### ISSUE TITLE
Advanced match rule when crawling

### ISSUE THREAD

**Issue by kslr** [lordfriend/Albireo#45]
First, can BANGUMI.MOE be able to customize the label?

I can only use fixed tags when I add "sin七宗罪" and can not be retrieved effectively.
For example, the key words: "sin七宗罪 简体中文 mp4"
results:
![qq20170523-173231](https://cloud.githubusercontent.com/assets/5516323/26348001/dde745da-3fdd-11e7-9023-8da16193ebf0.png)

   "Sin Nanatsu no Taizai" and "sin Nanatsu no Taizai - Zangeroku" are different, but I can not pick out "sin Nanatsu no Taizai".

**Comment by lordfriend** [comment]
I have to say, currently,it is not be able to do this. because we use the API which bangumi moe use. Athough I've learned from the developer of bangumi.moe that there are another search API which is more flexible. But moving to that is a very different approach on this project.

So Currently I suggest you to use DMHY if you need some keyword match search instead of tag match search.

**Comment by kslr** [comment]
thanks for your advice.
I got the result, I was too careless
![qq20170523-185317](https://cloud.githubusercontent.com/assets/5516323/26351216/487ddb1a-3fe9-11e7-9f2c-e25d6be24ebf.png)
Some sets are negative, they will be what state? Is it neglected?

**Comment by lordfriend** [comment]
negative means a match miss, won't be downloaded
